spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/jpastudy
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

# spring.redis.host=localhost
# spring.redis.port=6379